# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "catlamp"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "yfxu.srht.site"
tags = []
features = []
min_version = "0.106.0"

[author]
  name = "Yifei"
  homepage = ""
